#!/bin/bash

set -e

function print_usage {
    echo "Usage: $0 [sh] [PromQL Query]"
    echo " -s scatter - Use scatter plot."
    echo " -h help    - Shows this usage."
}

[ -z "$1" ] && print_usage && exit 1

scatter=false

while getopts 'sh' flag; do
  case "${flag}" in
    s) scatter=true && shift 1 ;;
    h) print_usage ; exit 1 ;;
  esac
done

export CAPI_ADDR=$(cat ~/.cf/config.json | jq -r .Target | sed 's|https|http|')
export SPACE_ID=$(cat ~/.cf/config.json | jq -r .SpaceFields.GUID)
export LOG_CACHE_ADDR=$(cat ~/.cf/config.json | jq -r .Target | sed 's|api|log-cache|' | sed 's|https|http|')
export TOKEN=$(cf oauth-token)
export SCATTER_PLOT=$scatter

promql-plotter "$@"
